### ISSUE TITLE
Update IUPHAR target cross ref URL

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#12]
IUPHAR is now Guide to Pharmacology. Have updated the urls in the xref_source table, but need to check if reflected on the Target Report Card e.g., CHEMBL5868

New URL should be:
http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=598

And base URL for 'IUPHAR' link should be:
http://www.guidetopharmacology.org

Should also change the name to 'Guide to Pharmacology' (let me know if this needs to be done in the db)

**Comment by mark-davies** [comment]
New name and links added: http://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL5868

No need to change anything in the database - but if you do let me know

**Comment by agaulton** [comment]
one more thing - do the iuphar links come from component_xref or target_xref table?

**Comment by mark-davies** [comment]
They come form the target_xrefs table
