### ISSUE TITLE
Add new entries to Downloads page

### ISSUE THREAD

**Issue by madgpap** [chembl/user_interface#19]
https://www.ebi.ac.uk/chembl/downloads

1) Add entries SureChEMBL and UniChem FTPs:
ftp://ftp.ebi.ac.uk/pub/databases/chembl/SureChEMBL/
ftp://ftp.ebi.ac.uk/pub/databases/chembl/UniChem/

2) Update several entries, e.g. mychembl, ChEMBL NTD
3) Update the order to ChEMBL, SureChEMBL, UniChem, myChEMBL, ChEMBLRDF, ChEMBLNTD, etc .

**Comment by ndedman** [comment]
Updated for ChEMBL 21
