### ISSUE TITLE
Setup new Cell Line pages

### ISSUE THREAD

**Issue by mark-davies** [chembl/user_interface#2]
Requires:
1. Cell search ability 
2. Report card page
3. Widget update

**Comment by mark-davies** [comment]
Searching by cell terms is now possible on wwwdev, new functionality includes:

1. New cell search button
2. Cell Report card page with summary and widget sections
3. Cell information (id, chembl_id and name) added is hidden columns on bioactivity pages
4. Possible to down cell search results

**Comment by agaulton** [comment]
Looks great! Where there is a LINCS ID, can we add a hyperlink?
e.g., http://life.ccs.miami.edu/life/summary?mode=CellLine&source=LINCS&input=LCL-1410

**Comment by mark-davies** [comment]
LINCS links added

**Comment by agaulton** [comment]
Could we just change the name for this link to 'LINCS project'?
Ta

**Comment by mark-davies** [comment]
Changed - although I used a 'P' instead of 'p', as looked right. If this needs changing again let me know

**Comment by agaulton** [comment]
One last thing - on the cell search results, could the links to CLO/EFO/LINCS open in a new page/tab?

**Comment by mark-davies** [comment]
Links now open in new page/tab
