### ISSUE TITLE
LHS menu cleanup

### ISSUE THREAD

**Issue by madgpap** [chembl/user_interface#20]
-Add a mychembl link
-Remove unsupported, deprecated stuff, e.g. sarfaris, drugEBIlity...

![image](https://cloud.githubusercontent.com/assets/3305715/10375561/209e466e-6df1-11e5-8171-3fc29c12f23d.png)

**Comment by madgpap** [comment]
also move SureChEMBL link towards the top - say 3rd position.

**Comment by ndedman** [comment]
Done
