### ISSUE TITLE
Remove IBM patents from UniChem cross-refs

### ISSUE THREAD

**Issue by madgpap** [chembl/user_interface#25]
For ChEMBL_20, I would like to remove the cross refs to IBM patents (source 13 in UniChem) on the compound report card.

The reasons are:
* In case of drugs, too many patent links are provided (see below)
* The IBM mapping between the compound and patents is out of date and incomplete.
* We now have SureChEMBL UI/flat files/data client/Open PHACTS that provide authoritative and timely links to patents.
* The InChI to patent ID map abuses the UniChem design philosophy and will likely be deprecated.  

![image](https://cloud.githubusercontent.com/assets/3305715/11559475/0d3c4abc-99b1-11e5-82d0-eb11f0eda0ef.png)

**Comment by anne123** [comment]
I agree this doesn't look good but would it be better to just show the first few and then have a "more" link as we do for the target predictions?  To me the question is if this data is in UniChem do we want to be selective about which datasets we link to?

**Comment by madgpap** [comment]
A 'more...' button would tidy up the table but it wouldn't solve the other issues above. We have discussed before about deprecating/hiding this source from UniChem mainly as it does not comply with the InChI-->compound ID mapping. So, what we could do is deprecate it directly in UniChem so that it doesn't appear in the ChEMBL UI either.

**Comment by ndedman** [comment]
And then it will no longer appear in the SureChEMBL report card either.

**Comment by madgpap** [comment]
Jon effectively deprecated source 13 by flagging it as private. As a result, it does not appear in the UniChem UI and web services and thus neither on the ChEMBL/SureChEMBL compound report cards: 
![image](https://cloud.githubusercontent.com/assets/3305715/11623714/a1832f70-9cc6-11e5-9515-4fb281981574.png)

closing issue.
