### ISSUE TITLE
Browse Drug Indications tab

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#28]
Similar to the Browse Drug Targets tab, this should show information from the drug_indication and indication_refs table. The query should be same principle as the Browse Drug Targets tab - i.e. show the parent compound  with molecule_chembl_id, image, molecule_type, first_approval, atc_code, atc_code_description and usan_stem (some of these are hidden by default), then from drug_indications show mesh_id (hyperlinked e.g.,https://id.nlm.nih.gov/mesh/D009765.html) mesh_heading, efo_id (hyperlinked e.g. http://www.ebi.ac.uk/efo/EFO_1000621), efo_term, and then info from the indication_refs table concatenated the same as on the Browse Drug Targets tab.

**Comment by ndedman** [comment]
I'm just doing this now. Will commit to SVN later.

**Comment by ndedman** [comment]
![screen shot 2016-02-09 at 17 17 42](https://cloud.githubusercontent.com/assets/6928576/12924258/17f27cd0-cf51-11e5-8b13-724d6f063930.png)

Almost complete - just ironing out some sorting bugs.

**Comment by agaulton** [comment]
Sorry, having seen this, please can we remove ATC code + description and USAN stem (I think these will be confusing as they won't necessarily relate to the indication). If we could add USAN year (from molecule_dictionary) and max_phase_for_ind (from drug_indication)? Also is it poss to show the drug name under the image, rather than the ChEMBL_ID (and have CHEMBL_ID as an optional field), like we do on the browse drug targets tab?

**Comment by ndedman** [comment]
Looks like this now:
![screen shot 2016-02-10 at 15 39 20](https://cloud.githubusercontent.com/assets/6928576/12951921/86a8f86e-d00c-11e5-8fe2-dceda769cef4.png)

ChEMBL ID is a hidden field (I've not kept any others - do you want to add some back?)

Also, the EFO ID has some other ontologies listed, so I've linked out to some other ontology services when I couldn't perform a lookup at EBI (although they might exist via another route).
```javascript
if (data.substring(0,2) == 'EF') {
   return "<a target='_blank' href='http://www.ebi.ac.uk/efo/"+data.replace(':','_')+"'>"+data+"</a>";
};
 
 if (data.substring(0,2) == 'HP' || data.substring(0,2) == 'DO') {
   return "<a target='_blank' href='http://purl.obolibrary.org/obo/"+data.replace(':','_')+"'>"+data+"</a>";
};

if (data.substring(0,2) == 'Or') {
   return "<a target='_blank' href='http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert="+data.split(':')[1]+"'>"+data+"</a>";
};
						
if (data.substring(0,2) == 'MP') {
   return "<a target='_blank' href='http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=MP&termId="+data+"'>"+data+"</a>";
};
```

**Comment by ndedman** [comment]
Just noticed that the filtered download doesn't reflect the table contents. WIll fix.

**Comment by agaulton** [comment]
Is it possible to concatenate the references (like on the Browse Drug Targets tab) so that if there are multiple references for a drug-indication combination, we don't duplicate rows (e.g., Levodopa has two refs for Parkinson's disease)?

**Comment by ndedman** [comment]
I'm looking at this now. Unfortunately, the concatenation is causing problems since some compounds (Imipramine) have a lot of references. I may try and do this in PHP.

**Comment by agaulton** [comment]
OK thanks, An alternative, if Patricia agrees, might be to just show the first 3 or so references for each drug-indication?
A

**Comment by agaulton** [comment]
Fine by me. I think it's better to show a fixed maximum number of references since there's a number of compounds with several DailyMed references.

Thanks,
Patricia

**Comment by ndedman** [comment]
We can keep the downloads for this as is, so all references are available.
Nathan
On 20 Feb 2016 17:04, Anna Gaulton <notifications@github.com> wrote:Fine by me. I think it's better to show a fixed maximum number of references since there's a number of compounds with several DailyMed references.

Thanks,
Patricia

**Comment by ndedman** [comment]
Looking at the code and the data, the mechanism refs in the Browse Drug Targets tab are pre-concatenated in the table (multiple delimiters). I'm just trying to split the query out into two now, calling the refs while the table is being built. We may have to go for a materialised view.

**Comment by agaulton** [comment]
I'm happy to build a view for the indications similar to drug_targets_mv if it helps, just let me know.

**Comment by ndedman** [comment]
I think this might be the best course of action. I'm wrestling with the SQL and since I'm trying to integrate this with the existing table logic, it's not really working.

**Comment by agaulton** [comment]
ok will take a look now

**Comment by agaulton** [comment]
Sorry for delay - sidetracked by another bug. Have created a view: drug_indications_mv. In the end I used a PL/SQL function to concatenate the references. I've restricted the length of refs to 2000, but I can change this easily depending on how it looks. I also copied the view format from the drug mechanism one, so I've included all the other drug-related columns, though don't know if you need them (maybe in downloads).

**Comment by ndedman** [comment]
Thanks Anna.

It sounds like the query I ran - 15mins would be a bit of a wait in the UI!

We can tweak the number of Refs but 3 distinct ones might the best visually.

**Comment by agaulton** [comment]
Tested, fine now
