### ISSUE TITLE
Fix DailyMed cross refs on compound report card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#29]
DailyMed website changed and cross refs no longer work. E.g., on https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL192, link in Compound Cross References is http://dailymed.nlm.nih.gov/dailymed/advSearch.cfm?startswith=NAME:sildenafil%20citrate but no longer works. New link is: http://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sildenafil%20citrate I think (but there might be a better way if you check out their API docs). The search terms to used are stored in the compound_xref table

**Comment by ndedman** [comment]
I had a brief look at the API documentation and couldn't really find anything regarding /search and I think it's a URL generated for the page search.

It's fixed for next release.
