### ISSUE TITLE
View of metabolism data on compound report card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#30]
Details TBC!

**Comment by agaulton** [comment]
Let me know if you need any info on this (table details etc)

**Comment by ndedman** [comment]
I might need to pick your brains about this. Just updating the indications table at the moment.
Rough query output so far:
<img width="807" alt="screen shot 2016-02-22 at 11 45 02" src="https://cloud.githubusercontent.com/assets/6928576/13217373/dcfbc402-d959-11e5-9081-07a37d4ff047.png">

**Comment by agaulton** [comment]
Yep no prob. Let me know what you need, or if you want to Skype.
It looks nice (though I haven’t checked the data). Are the blank ones where we don’t have a structure? Would it be possible to add a name (compound_records.compound_key)?
A

**Comment by ndedman** [comment]
There's lots to tweak on this yet, I"m just trying out queries to get the correct hierarchy to give metabolism paths that make sense. It may have to split this out into more than one query.

**Comment by ndedman** [comment]
I can't get this to look sensible at the moment, so I think this will be a feature to come at a later date.

**Comment by agaulton** [comment]
That’s fine

**Comment by mnowotka** [comment]
Hi Nathan,  since we need this for the new interface as well I'm reassigning this issue to David. Please point us to the code you've written so far.

**Comment by ndedman** [comment]
So far, there is a [view](http://howe.ebi.ac.uk:8080/svn/starlite_interface/trunk/system/application/views/application/compound/report_card/metabolites.php) in the report card and a function [get_metabolites](http://howe.ebi.ac.uk:8080/svn/starlite_interface/trunk/system/application/models/chembl.php) in the chembl model. The [compound controller](http://howe.ebi.ac.uk:8080/svn/starlite_interface/trunk/system/application/controllers/compound.php) passes through the OCI object.

**Comment by mnowotka** [comment]
Can I close this one?

**Comment by agaulton** [comment]
Almost... We noticed one thing - on this page:
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL3508144
the image for the compound is missing in the metabolism view - I'm guessing indigo fails to generate for some reason? Is it possible to default to the ChEMBL image in such a case?

**Comment by agaulton** [comment]
Sorry this is actually the compound that has the problem: 
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL3706501

**Comment by nclopezo** [comment]
Actually, it defaults to a ChEMBL image when there is no structure data available, that is the case in which indigo fails to generate the image. 

For example:
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL49429
https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/73070

What is happening in this case is that the visualisation images are using the current production server, which uses chembl21, so the image requested is not found:

https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL3706501.svg
https://www.ebi.ac.uk/chembl/compound/displayimage_large/2038536

When the production server uses chembl22 the images should work:

https://wwwdev.ebi.ac.uk/chembl/api/data/image/CHEMBL3706501.svg
https://wwwdev.ebi.ac.uk/chembl/compound/displayimage_large/2038536

If you want I can make the code to use temporarily wwdev.

**Comment by mnowotka** [comment]
No, I assume we will release UI and API at the same time.

**Comment by agaulton** [comment]
Ok that's fine then. Can close
