### ISSUE TITLE
Review target cross references

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#31]
Some of these should come from the component_xref table, some from the target_xref table. Would be good to know where the code is currently looking, as I'm not sure all are coming from the correct place? Then I can clarify which should be from where, or create a view with all in.

**Comment by ndedman** [comment]
For the target xrefs it appears to be pulling from the target_xref table.

I've added the code to a repo on sark, so you can see the code since Trac is broken.

[Git repo on Sark](http://sark.ebi.ac.uk:9090/?p=chembl_interface.git;a=blob;f=starlite_interface/system/application/models/chembl.php;h=799aaf3359c7f784e413362a2472563fb771ae7e;hb=e6a36bb64e50b71247a0d06f774e4c2487b2a13c#l1704)

**Comment by agaulton** [comment]
Let's postpone

**Comment by mnowotka** [comment]
What's the status of this one?

**Comment by agaulton** [comment]
For SINGLE PROTEIN targets (e.g., https://www.ebi.ac.uk/chembl/target/inspect/CHEMBL210), the cross references (to ArrayExpress, GO, Reactome, Interpro etc) should come from the component_xref table, not the target_xref table. 

There may be a few exceptions, I will go through and check. But in general, if the source exists in the component_xref table, it should come from there. 

I will clean up the tables and check the URLs are all correct. Can you confirm whether the URLs used on the interface come from the xref_source table or are hard-coded?

**Comment by ndedman** [comment]
Looks like it's coming from the target_xref:
```sql
SELECT DISTINCT xref_id, xref_name
			FROM target_xref
			WHERE tid=$tid
			AND xref_src_db='$src'";

		
```
I'll change and deploy to dev.

**Comment by ndedman** [comment]
Deployed to development. I've also widened the card tables, to allow for the long descriptions avoiding text wrapping.

https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL210

**Comment by agaulton** [comment]
I tidied up the target_xref and component_xref tables. It is now the case that some target cross references should come from the target_xref table (ComplexPortal, Wikipedia, canSAR-Target, MICAD) and for SINGLE PROTEIN targets the rest should come from the component_xref table. Nathan already looked at some of this, so may be ok already. So the query should be something like:

select xref_src_db, xref_id, xref_name from target_xref where tid = ?
union
select x.xref_src_db, x.xref_id, x.xref_name from target_dictionary d, target_components tc, component_xref x where d.tid = tc.tid and tc.component_id= x.component_id and d.target_type = 'SINGLE PROTEIN' and d.tid = ?

The layout etc can all stay the same, just the underlying query changes...

Also please could we check the URLs that are linked to (both for the name of the resource and the ID link) as some of these have changed. I'm not sure whether these are hard-coded somewhere, but there is a table called xref_source that has the up-to-date information.

Finally, can we also add a link in the 'Target cross references' - protein section to 'Pharos' (cross ref info already in the component_xref table)?

**Comment by nclopezo** [comment]
I updated the query for getting the references, now it will be:

```sql
(select txref.xref_id, txref.xref_name 
from target_xref txref where txref.tid = $tid and txref.xref_src_db='$src')

union

(select x.xref_id, x.xref_name 
from target_dictionary d, target_components tc, component_xref x 
where d.tid = tc.tid and tc.component_id= x.component_id and d.target_type = 'SINGLE PROTEIN' and d.tid = $tid and x.xref_src_db='$src')
```

In the code, the data is queried per source database. 

I also saw that the URLs are hard-coded in the php code. I will modify it to get them from the database. And I will also add the new section.

I see that in XREF_SOURCE now there are less entries in Chempro. I guess that the latest information is there and the others were removed, right?

**Comment by nclopezo** [comment]
I also would like to ask, is it ok if I make the links to open in a new tab? In this way, when the user is looking at the report card and clicks on a reference, it opens a new tab instead of using the tab that is currently open.

**Comment by agaulton** [comment]
Yep I think this makes sense!

**Comment by nclopezo** [comment]
- Now the links open in a new tab:
https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL1293232

- All the urls are generated from the xref_source table and are no longer hardcoded. 

- The Pharos section was added. The development server connects to chempub, this it what it shows when I make it connect directly to chempro: 

For example, for CHEMBL2250: 

![screen shot 2016-06-29 at 09 27 02](https://cloud.githubusercontent.com/assets/1944922/16445696/cd448454-3ddb-11e6-985d-c65f7c170825.png)

And the full url of the link is https://pharos.nih.gov/idg/targets/P51451

**Comment by agaulton** [comment]
Couple of minor things:
* For Guide to Pharmacology, can we remove the () (i.e., if there is no xref_name then display nothing apart from the ID). 
* For Pharos, can we add the xref_name e.g., Pharos  P51451 (Tchem)
* Can we also add links to Open Targets in the Protein section. These should only be on pages where the target_type is 'SINGLE PROTEIN' and the Organism is 'Homo sapiens'. The link should use the Ensembl Gene ID e.g., https://www.targetvalidation.org/target/ENSG00000136573/associations

**Comment by nclopezo** [comment]
I changed the links layout:

https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL214
https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL1293232

I also added the Open Targets links but it seems that they don't have results always:
https://www.targetvalidation.org/target/ENSG00000277773/associations
Is this OK?

**Comment by agaulton** [comment]
Tiny thing - can we move the Open Targets link up to keep the alphabetical order in this section?
I think it is fine if there are a few genes for which open targets doesn't have data since it resolves to a sensible message, and might have data in future.
Thanks

**Comment by nclopezo** [comment]
I moved the section:
https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL214

**Comment by agaulton** [comment]
Great thanks.
Also on this page:
https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL214
the Guide to Pharmacology link looks a bit odd - it has two links? Also should be before 'Human protein atlas'?

**Comment by nclopezo** [comment]
I will check the order again. 

For the link, the query that it does is:

```SQL
(select txref.xref_id, txref.xref_name 
  from target_xref txref where txref.tid = 51 and txref.xref_src_db='GuideToPHARMACOLOGY')
  union
  (select x.xref_id, x.xref_name 
  from target_dictionary d, target_components tc, component_xref x 
  where d.tid = tc.tid and tc.component_id= x.component_id and d.target_type = 'SINGLE PROTEIN' and d.tid = 51 and x.xref_src_db='GuideToPHARMACOLOGY');
```

And the results that it is getting are:

![screen shot 2016-09-15 at 14 38 38](https://cloud.githubusercontent.com/assets/1944922/18551865/31ac70ec-7b52-11e6-98a3-a160c5072779.png)

What should be done in this case?

**Comment by agaulton** [comment]
Sorry, my bad. Fixed in the database now
