### ISSUE TITLE
Update releases and DOIs

### ISSUE THREAD

**Issue by madgpap** [chembl/user_interface#32]
Here:
https://www.ebi.ac.uk/chembl/downloads

![image](https://cloud.githubusercontent.com/assets/3305715/12824646/26a062a0-cb6a-11e5-8460-770d6003b4d0.png)

**Comment by madgpap** [comment]
myChEMBL and RDF

**Comment by ndedman** [comment]
Updated but not committed yet.
<img width="936" alt="screen shot 2016-02-05 at 12 00 22" src="https://cloud.githubusercontent.com/assets/6928576/12845767/229e14ea-cc00-11e5-882c-36a58387e0b9.png">

**Comment by agaulton** [comment]
typo in RDF release DOI? 20.1 instead of 21.0?

**Comment by agaulton** [comment]
oh I see ignore that - this was an incremental update?

**Comment by ndedman** [comment]
Yes. I can take it out?
