### ISSUE TITLE
Indications on compound report card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#33]
Could we add a section (only where data available) on compound report card called "Indications" that displays MeSH_ID, MeSH_heading, EFO_ID, EFO_term and max_phase_for_ind (call it "Max Phase for Indication") from drug_indication table. Will need to join to molecule_hierarchy so that we show this on the parent page as well as for salts (see how the mechanism_of_action section works)

**Comment by ndedman** [comment]
Done and deployed, although not appearing. Currently investigating.

Should look like this:
![screen shot 2016-02-16 at 17 25 26](https://cloud.githubusercontent.com/assets/6928576/13084711/6581b692-d4d2-11e5-83ab-1aa2898b632a.png)

**Comment by ndedman** [comment]
Fixed. PHP 5.3.3 doesn't handle implicit array indices. Split onto a new line.

**Comment by ndedman** [comment]
Can I close this?

**Comment by agaulton** [comment]
I don’t know - I still haven’t been able to get a compound_report card to open - always seems to timeout…

**Comment by mnowotka** [comment]
@agaulton - can we close it now?

**Comment by mnowotka** [comment]
pinging @agaulton :)
