### ISSUE TITLE
Links to Cellosaurus

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#35]
On Cell search results and Cell Report Card, we can now add hyperlinks to Cellosaurus (where there is an ID). The URL is e.g., http://web.expasy.org/cellosaurus/CVCL_0030 (for http://www.ebi.ac.uk/chembl/cell/inspect/CHEMBL3308376)

**Comment by ndedman** [comment]
Done

**Comment by agaulton** [comment]
Tested
