### ISSUE TITLE
Activity Source Filter

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#36]
May need to add new data sources to this manually. 
New for chembl_21 are:
FDA Approval Packages (src_id = 28)
GSK Kinetoplastid Screening (src_id = 29)
St Jude Leishmania Screening (src_id = 32)
Gates Library compound collection (src_id = 33)

Also Guide to Receptors and Channels (src_id= 10) is now removed

**Comment by ndedman** [comment]
Done

**Comment by agaulton** [comment]
Tested
