### ISSUE TITLE
Widgets not currently appearing

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#37]
on report cards - could just be to do with dev setup though...

**Comment by ndedman** [comment]
Just noticed that the dev instance is still an earlier commit. Will fix.

**Comment by ndedman** [comment]
Page currently takes approximately 8 minutes to load locally - on dev this will redirect to the error page.

**Comment by ndedman** [comment]
Queries need to be cached - see info from Mark (not on confluence page).
