### ISSUE TITLE
Keep the 'similarity' column in the downloads file

### ISSUE THREAD

**Issue by ljbellis** [chembl/user_interface#38]
If a user has run a compound similarity search, the resulting table shows the percentage similarity:

![sim](https://cloud.githubusercontent.com/assets/9843928/13577203/361cf30a-e489-11e5-9dc3-1e9274a6ae00.jpg)

However, when the user then downloads the results file, either as an SDF or Tab, this column is not present.

Please could you look into whether this could be kept in?

**Comment by nclopezo** [comment]
I fixed it and it is now deployed in production.

**Comment by mnowotka** [comment]
@ljbellis  - can you please check if this is OK?

**Comment by ljbellis** [comment]
Yes this works. thank you.
