### ISSUE TITLE
Mechanism refs missing & malformed links

### ISSUE THREAD

**Issue by ndedman** [chembl/user_interface#39]
1. in browse_drug_targets, if you search for ‘serelaxin’ (molregno 1380624) you’ll find two mechanisms of action: ‘Relaxin receptor 1’ and ‘Relaxin receptor 2’;
if you click on ‘Relaxin receptor 2’ (the one with no mechanism refs), it takes to the target report card and there one should find ’serelaxin’ under the ‘Approved Drugs and Clinical Candidates’ section, but instead no section is displayed. We think this is due to the fact that there’s no mechanism references for these target and potentially there should be an outer join (instead of a join) to the mechanism_refs table.

2. in browse_drug_targets, if you search again for ’serelaxin’, there’s three refs for ‘Relaxin receptor 1’ but only one, the PubMed ref, is working. There’s different reasons why the other two references do not work:

 - for the first reference ‘Other’, the ref_url in the mechanism_refs table is null (despite the fact there’s a ref_id). Ideally these cases should not be displayed in the interface.

 - for the second reference “Other’, the ref_url from the mechanism_refs tables is in the interface preceded by the ebi/chembl url and therefore the link doesn’t work properly.
The url that precedes the ref_url is even different depending on which page you are (as expected)
- in the target report card for ‘Relaxin receptor 1’, the link is pointing to 'https://www.ebi.ac.uk/chembl/target/inspect/www.ema.europa.eu/docs/en_GB/document_library/EPAR_-_Public_assessment_report/human/002817/WC500171911.pdf'
- in the browse_drug_targets it is pointing to 'https://www.ebi.ac.uk/chembl/drug/www.ema.europa.eu/docs/en_GB/document_library/EPAR_-_Public_assessment_report/human/002817/WC500171911.pdf'.
As you can expect, in both cases the link should point to 'www.ema.europa.eu/docs/en_GB/document_library/EPAR_-_Public_assessment_report/human/002817/WC500171911.pdf'.

**Comment by ndedman** [comment]
Javascript updated to fix the malformed Mechanism refs. Awaiting data fix on MV.

**Comment by mnowotka** [comment]
Is that deployed?

**Comment by ndedman** [comment]
Committed to trunk but I don't think it made it to the last deployment.

**Comment by mnowotka** [comment]
OK, once this is fully finished, can you please deploy it so @agaulton can take a look and close this issue?

**Comment by ndedman** [comment]
The first part of the problem outlined above is due to data missing in a materialised view, so I've only solved the malformed attachment URLS. I'll deploy now.

**Comment by agaulton** [comment]
So I think 1) is still an issue: https://www.ebi.ac.uk/chembl/target/inspect/CHEMBL1628482
The Approved Drugs and Clinical Candidates section isn't shown. This is probably because of a join to mechanism_refs (no refs in this case). I think we should assume there could be no refs and outer join here. Let me know if this query is using the view though - I don't think it is. There is also the same issue on the Compound Report Card: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2108358 as only one of the two targets is shown.

Also 3) is still not working (at least the second 'Other' link should work) - could we also put a fix on the report cards so that if the url starts with www instead of http it still works?

The other issues are due to data - missing URLs. The fix you made seems to work but might not in every case. I will fix the data but lets discuss...

**Comment by ndedman** [comment]
OK, I need to take another look at the query - I think I may have missed something. The Javascript fix I deployed works for me, with all 3 references now pointing to the correct URLs:

``` html
<a target="_blank" href="http://assets.escardio.org/assets/Presentations/OTHER2013/Davos/Day%203/17-Serelaxin.pdf">Other</a><br>
<a target="_blank" href="http://www.ema.europa.eu/docs/en_GB/document_library/EPAR_-_Public_assessment_report/human/002817/WC500171911.pdf">Other</a><br>
<a target="_blank" href="http://europepmc.org/abstract/MED/23141816">PubMed</a><br><a target="_blank" href="undefined"></a><br>
```

**Comment by agaulton** [comment]
On which page? It's fine on browse drug targets now, but not on Target Report Card

**Comment by ndedman** [comment]
Ah, apologies, I missed that. Will fix.

**Comment by ndedman** [comment]
It looks like it's already an outer join on mechanism_refs.mec_id:

```sql
SELECT DISTINCT md.chembl_id,
  md.molregno,
  md.pref_name,
  md.max_phase,
  dm.mechanism_of_action,
  wm_concat(DISTINCT mr.ref_type
  ||'$$'
  ||mr.ref_id
  ||'$$'
  ||mr.ref_url
  ||'####') AS mechanism_refs
FROM drug_mechanism dm,
  molecule_dictionary md,
  mechanism_refs mr
WHERE dm.molregno=md.molregno
AND mr.mec_id(+) = dm.mec_id
AND dm.tid       = 103801
AND lower(mr.ref_type) NOT LIKE 'wikipedia'
AND dm.downgraded IS NULL
GROUP BY md.chembl_id,
  md.molregno,
  md.pref_name,
  md.max_phase,
  dm.mechanism_of_action
ORDER BY md.max_phase DESC;
```
I will dig further.

**Comment by agaulton** [comment]
Need it on the ref_type NOT LIKE ‘wikipedia’ bit too I think e.g., 


SELECT DISTINCT md.chembl_id,
  md.molregno,
  md.pref_name,
  md.max_phase,
  dm.mechanism_of_action,
  wm_concat(DISTINCT mr.ref_type
  ||'$$'
  ||mr.ref_id
  ||'$$'
  ||mr.ref_url
  ||'####') AS mechanism_refs
FROM drug_mechanism dm,
  molecule_dictionary md,
  mechanism_refs mr
WHERE dm.molregno=md.molregno
AND mr.mec_id(+) = dm.mec_id
AND dm.tid       = 103801
AND lower(mr.ref_type (+)) NOT LIKE 'wikipedia'
AND dm.downgraded IS NULL
GROUP BY md.chembl_id,
  md.molregno,
  md.pref_name,
  md.max_phase,
  dm.mechanism_of_action
ORDER BY md.max_phase DESC;

**Comment by ndedman** [comment]
Changes deployed to [Dev](https://wwwdev.ebi.ac.uk/chembl/).

**Comment by agaulton** [comment]
Refs and Target Report Card, but still missing relaxin receptor 2 from Mechanism of Action section of Compound Report Card: https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL2108358 (same issue with join I guess)

**Comment by ndedman** [comment]
The second query is directly underneath - I thought I'd updated that also. Deployed to dev.

**Comment by agaulton** [comment]
Looks good now, thanks
A

**Comment by ndedman** [comment]
I'll deploy to live now.

**Comment by mnowotka** [comment]
@agaulton - is that fixed now, can I close this issue?

**Comment by agaulton** [comment]
Yes fixed. Will correct underlying data in IDG too, but may need to revisit to check all looks ok for chembl_22.
