### ISSUE TITLE
Add Structural Alert section 

### ISSUE THREAD

**Issue by mark-davies** [chembl/user_interface#4]
Setup new structural alert section on the compound report card. This will probably require an additional new page to display all structural alerts.

Also need to decide how images will be generated.

**Comment by mark-davies** [comment]
New structural alerts section added to the compound report card and a new page created to display all alerts. Some example pages:

http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL155263
http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL1082532
http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL360923 (Compound with most alerts, 42)

**Comment by agaulton** [comment]
This is great, but quite easy to miss on the page - is there a way to make it a bit more obvious, perhaps just a little more space above/below, or a box around the text/link? And maybe show even if there are no alerts i.e., 'there are no alerts for this compound'?

**Comment by mark-davies** [comment]
Structural alerts will always be shown and I have moved above the Alternate Forms section, so that it stands out more.

Example with structural alert: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL155263
Example without structural alert: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL941

**Comment by agaulton** [comment]
Yep, I think this is better, thanks

On 23 Jan 2015, at 15:30, Mark Davies <notifications@github.com> wrote:

> Structural alerts will always be shown and I have moved above the Alternate Forms section, so that it stands out more.
> 
> Example with structural alert: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL155263
> Example without structural alert: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL941
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Anna Gaulton

Senior Data Integration and Development Officer, ChEMBL
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom


Tel:  +44 1223 492690
