### ISSUE TITLE
Add pubchem links/AIDs to assays

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#40]
On Assay Report Card, if an assay comes from PubChem (src_id = 7), show assays.src_assay_id field and link to PubChem BioAssay e.g., for CHEMBL1738445:

[AID:2135](https://pubchem.ncbi.nlm.nih.gov/bioassay/2135)

**Comment by nclopezo** [comment]
I added a new row to the table, see for example: 

![chembl1614400](https://cloud.githubusercontent.com/assets/1944922/14784176/24089e88-0aec-11e6-8534-10e4deca26d8.png)

The row doesn't appear when src_id != 7:

![chembl615155](https://cloud.githubusercontent.com/assets/1944922/14784276/ab1bdb42-0aec-11e6-876b-1056344a1163.png)

Is this ok?

**Comment by agaulton** [comment]
Looks great. Thanks

**Comment by mnowotka** [comment]
Deployed to production.
