### ISSUE TITLE
Tissue information

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#42]
Info TBC...

**Comment by mnowotka** [comment]
We need to discuss do we have time to prepare a separate tissue report card before the release or go for something easier.

**Comment by agaulton** [comment]
I think there is an issue with displaying the tissue report card - this one should only have a few (20) assays linked to it, so I don't *think* the issue is a timeout...
https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638236

**Comment by nclopezo** [comment]
I found the issue, php 5.3 doesn't allow [direct access to the array returned by a function](http://stackoverflow.com/questions/1459377/access-array-returned-by-a-function-in-php). 
It should be fixed now: 
https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638236

**Comment by agaulton** [comment]
A couple of other things: 
* The link to EFO ID doesn't work properly. 
e.g., it's fine for https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638182
because the prefix is EFO, but for 
https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638236
it doesn't work because it appends an EFO prefix onto an Uberon ID and finds the wrong term. I would suggest displaying the full ID with the prefix and linking with that.

* Also please could we add two more IDs (I added these to the tissue_dictionary since we made the report card): BTO_ID and CALOHA_ID. BTO_ID can also be linked to Ontology Lookup Service e.g., http://www.ebi.ac.uk/ols/search?q=BTO:0000131&groupField=iri&exact=on&start=0
CALOHA does not have a link at present. Also add to the tissue search results page.

**Comment by nclopezo** [comment]
I removed the prefixes. And I added the BTO and CALOHA ids. For the CALOHA ids I didn't add any link. I would like to confirm that this is correct. 
https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638182
https://wwwdev.ebi.ac.uk/chembl/tissue/inspect/CHEMBL3638236

**Comment by nclopezo** [comment]
The fields are also in the search results page now.

**Comment by agaulton** [comment]
Looks good now thanks
