### ISSUE TITLE
Make sure that special characters in abstracts are displayed correctly

### ISSUE THREAD

**Issue by mnowotka** [chembl/user_interface#43]
Currently all document abstracts are missing special characters (example: https://www.ebi.ac.uk/chembl/doc/inspect/CHEMBL3525951). This is a complex problem because there are many levels where something can go wrong:

 - database encoding settings
 - php DB connector settings
 - html encoding

We need to make sure that everything is configured correctly and all the special characters are displayed fine.

This is also important for the new interface.

**Comment by nclopezo** [comment]
Despite the change in the php.ini file, The function htmlentities() was still using the wrong encoding. It seems that it is related to the php version used in the server. I added the parameter 'UTF-8' when this function is called in some parts of the code. 

`echo htmlentities( ..., 'UTF-8' );`

https://www.ebi.ac.uk/chembl/doc/inspect/CHEMBL3525951
