### ISSUE TITLE
Add columns to bioactivity summary view

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#45]
On the bioactivity summary view (ie.., the page you get to once you 'display bioactivities' for a target/compound etc) please can we add pChEMBL value as a default column after standard_units (it is already in the optional list)?

Can we also add published_type, published_value, published_units to the optional list (we will need to add them to the chembldb_bioactivity_summary view)?

**Comment by nclopezo** [comment]
The pChEMBL Value is now visible by default. 
And the other columns need to be added to the view before they are added to the table.

**Comment by agaulton** [comment]
Have rebuilt the chembldb_bioactivity_summary view with the extra columns now (published_type, published_relation, published_value, published_units)

**Comment by nclopezo** [comment]
I added the new fields to the results table:

![screen shot 2016-09-07 at 12 09 07](https://cloud.githubusercontent.com/assets/1944922/18309989/04398618-74f4-11e6-8787-47313983f93b.png)

Once I have access to the svn repository and the development server I can deploy it there.

**Comment by agaulton** [comment]
Thanks - can we put the published_x columns in the list of columns that are hidden by default (if not already)

**Comment by agaulton** [comment]
Great thanks
