### ISSUE TITLE
Withdrawn drugs

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#46]
We have added a few new fields to the molecule_dictionary that we would like to display on the compound report card:

In top table under Max phase, if molecule_dictionary.withdrawn_flag = 1, add a section called 'Withdrawn' with value 'Yes'

Then below the 'molecule features' section, show another section called 'Withdrawal information' (again only if withdrawn_flag = 1) that shows molecule_dictionary.withdrawn_year, molecule_dictionary.withdrawn_country and molecule_dictionary.withdrawn_reason.

These fields have also been added to the molecule_browse_drugs table, so can be added as optional columns on the 'Browse Drugs' tab.

**Comment by agaulton** [comment]
Another thing - molecule_dictionary.availability_type can now have an additional value (-2) which corresponds to 'withdrawn'. Patricia made a new icon for this (for the molecule_features section on compound report card and browse drugs tab). Let me know what format you need, or I can forward the original powerpoint image.

**Comment by agaulton** [comment]
Troglitazone is an example of where the 'withdrawn' icon needs to appear in the molecule features - currently the last box is a ?
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL408#

**Comment by mnowotka** [comment]
@agaulton, can you send the icon, any vector format will be OK, but SVG is the best. For this release we'll take Patricia's icon but for the new interface we will need Spencer to redo this.

**Comment by agaulton** [comment]
The icons were all done in powerpoint originally so pdf is the probably best I can do I think!

**Comment by mnowotka** [comment]
I can convert PP to SVG.

**Comment by nclopezo** [comment]
I added the changes to the compound report card:
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL408

Regarding the icons, I see that they are being generating from https://www.ebi.ac.uk/chembltools/autoicon3/1,0,0,0,0,1,0,0,0,-2

I am not sure where is the code for this, we would need to add the new icon to https://www.ebi.ac.uk/chembltools/autoicon3

**Comment by mnowotka** [comment]
OK, let's do it tomorrow!

**Comment by nclopezo** [comment]
I found the code for the icons. I added a placeholder and it is in the development server now:
https://wwwdev.ebi.ac.uk/chembltools/autoicon3/1,0,0,0,0,1,0,0,0,-2

If you send me the new icon I can add it and deploy it.

**Comment by nclopezo** [comment]
I just added the icon, you can see it now in the report card: 
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL408

**Comment by agaulton** [comment]
Looks great, thanks
A

**Comment by agaulton** [comment]
All looks fine.
Last thing - please could we add withdrawn_year, withdrawn_country, withdrawn_reason (from the molecule_browse_drugs table) as hidden columns to the 'Browse Drugs' tab (and also the download)?

**Comment by nclopezo** [comment]
I added the columns to the 'Browse Drugs' tab and the download.

https://wwwdev.ebi.ac.uk/chembl/drugstore

**Comment by agaulton** [comment]
Great thanks
