### ISSUE TITLE
Formatting of references on Browse Drug Targets

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#50]
There is something a little funny with the formatting of some urls on the Browse Drug Targets view
e.g., filter the tab for 'serelaxin'
The 'Other' links in Mechanism Refs column have a double http prefix (but missing a colon) which breaks the link. This may be because Nathan added a fix last time (these urls originally didn't have a prefix) but we since corrected the data (so now they do). Can you check if anything is hard-coded or the logic is wrong - probably there is a substitution happening?
As an aside, the top link is now dead anyway - I may remove, but we should check that we would handle these correctly. The 'Other' link when you filter for 'Azd-7624' is also a similar problem, so it may be all 'Other' refs that are affected.

**Comment by nclopezo** [comment]
There was code in some places which appended the string 'http://' was appended when the link was 'Other' . I removed it, it should work now.

**Comment by mnowotka** [comment]
@agaulton - can we close this?

**Comment by agaulton** [comment]
Yes can close
