### ISSUE TITLE
Re-order Compound Report Card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#51]
Can we change this so that the order is as follows (essentially Alternative Forms and Molecule Features move up and Structural Alerts moves down) - obviously if no data exists, still skip the sections as currently:
Compound Name and Classification
Compound Representations
Alternate Forms of Compound in ChEMBL
Molecule Features
Mechanism of Action
Indications for xxx (and change this title to just 'Indications')
Clinical Data
Bioactivity widgets
Target Predictions
Calculated Compound Parent Properties
Structural Alerts
Compound Cross References
UniChem Cross References

**Comment by agaulton** [comment]
I forgot the Metabolism section - I would say this should be after Clinical Data and before Bioactivity widgets. I probably forgot other stuff too (let me know)

**Comment by nclopezo** [comment]
The order has been changed:

https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL25

According to the code there should be 2 more sections:
- 'HELM Notation'
- 'Biological Sequence'

But I don't see that they are being used. Or at least some of the variables needed to render these sections are not even being initialised.

**Comment by agaulton** [comment]
HELM and Sequences are only on certain pages (where the compound is a peptide/antibody)
e.g., https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL1201585

**Comment by nclopezo** [comment]
Ah ok, sorry, I didn't see it before. Is their position ok? They appear always after UniChem Cross References.

**Comment by agaulton** [comment]
For HELM and Biological Sequence, please could we put these between Clinical Data and Bioactivity Widgets (though most compounds with HELM may not have bioactivity data anyway)?

**Comment by nclopezo** [comment]
The sections HELM and Biological Sequence have been reorganised:
https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL1201585

**Comment by agaulton** [comment]
Great thanks
