### ISSUE TITLE
URL encoding of cross references

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#52]
DailyMed cross references on the compound report card already have URL-encoded identifiers in the database. It looks like this then gets encoded again, so you end up with an incorrect link

e.g., https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL192
The xref_id for the DailyMed link is 'sildenafil%20citrate', which would produce the URL:
http://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sildenafil%20citrate

However, when you click the link you actually get:
https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sildenafil%2520citrate

Would it be better for us to remove the URL encoding from the data? Is this a generic interface thing across all links etc?
btw this problem currently exists on production too.

**Comment by nclopezo** [comment]
I checked and across all the references there are some html encodings of other characters, not only for the space character (%20), and not only for DailyMed. If we remove the encoding it could change unexpectedly the behaviour of other parts of the interface that use the urls. 

The interface generates the link correctly:
http://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sildenafil%20citrate

But it seems that it's the dailymed website the one that encodes again the url for some reason. I made the interface replace the '%20' with a '+' and dailymed. 

https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sildenafil+citrate

https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL192

**Comment by agaulton** [comment]
OK thanks - so we leave the data the way it is for now?

**Comment by nclopezo** [comment]
Yes I think that it could cause some links in other unexpected sections of the interface to break.

**Comment by mnowotka** [comment]
@agaulton can we close this now?

**Comment by agaulton** [comment]
Yes
