### ISSUE TITLE
Update Drug Data Freeze date

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#53]
On Browse Drugs, Browse Drug Targets and Browse Drug Indications, can we update the 'Approved Drug Data Freeze' date to 'May 2016'?

**Comment by nclopezo** [comment]
The date was updated:

- [Browse Drugs](https://wwwdev.ebi.ac.uk/chembl/drugstore)
- [Browse Drug Targets](https://wwwdev.ebi.ac.uk/chembl/drug/targets)
- [Browse Drug Indications](https://wwwdev.ebi.ac.uk/chembl/drug/indications)

**Comment by agaulton** [comment]
Great thanks - tested, can close
