### ISSUE TITLE
Redundant entries in Browse Drug Indications

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#54]
E.g., for Grazoprevir we see two rows for 'CHRONIC HEPATITIS C INFECTION' that differ by max phase and indication refs. We should group this, so that we just show the highest phase (4) and group the two refs. I can fix this is the drug_indications_mv by removing the molregno field and just leaving parent_molregno (which is what we're showing anyway), but question is - is this materialised view also being used on Compound Report Card (where we do need to be able to distinguish the salts and parents)? Or is the Indications section on the Report Card querying the drug_indication table directly?

**Comment by nclopezo** [comment]
I checked and the section on the Report Card queries the drug_indication table directly. The drug_indications_mv is only used in the Drug Indications Browser.

**Comment by agaulton** [comment]
OK I have fixed the drug_indications_mv to deal with this now, so will just check on interface and the can close

**Comment by nclopezo** [comment]
It seems that it's working fine, I ran it locally: 
![screen shot 2016-09-06 at 14 12 56](https://cloud.githubusercontent.com/assets/1944922/18274866/75ae922e-743c-11e6-9fa1-826c7054bd99.png)

**Comment by nclopezo** [comment]
you can check now in the development server: https://wwwdev.ebi.ac.uk/chembl/drug/indications

**Comment by agaulton** [comment]
Great thanks
