### ISSUE TITLE
Sorting bug in browse drugs/targets/indications tabs

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#55]
We have just noticed that when you sort on one of the columns in these tabs (e.g., phase) the paging does not work correctly. 
E.g., on browse drug targets, sort by phase descending, then click links at the bottom to page 2, 3 etc. The data displayed in the table remains the same as on page 1 (might be in a different order, or at least overlapping drugs if not identical set).
I think the paging works fine until you change the sorting.

Also there is a long standing issue that the last row on one page becomes the first row on the next page (so though page 2 says it is displaying 11-20, it is actually displaying rows 10-19). I don't know if this can easily be fixed though...

**Comment by nclopezo** [comment]
This has been fixed, you can check it now:
https://wwwdev.ebi.ac.uk/chembl/drugstore

When the data was sorted by some field, inside a "group" the order was not always the same. for example, when you sorted by max phase, within all the items that are 4 the order was not the same between sql queries. I made it always sort by molregno in addition to the current sorting. 

The second issue was also fixed.

**Comment by agaulton** [comment]
Thanks
