### ISSUE TITLE
Update compound properties

### ISSUE THREAD

**Issue by mark-davies** [chembl/user_interface#6]
Include new RO5 and possible hide others

**Comment by anne123** [comment]
I suggest removing MedChemFriendly and NumAlerts to remove confusion with new structural alerts that are to be added. PSA might be a property worth adding to the interface instead.

**Comment by mark-davies** [comment]
Property section updated

Added: PSA, HBA, HBD, HBA (lipinski), HBD (lipinski), RO5 (lipinski)
Removed:  MedChemFriendly, NumAlerts, R03

Example link: https://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL941
