### ISSUE TITLE
Edit activity source filter

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#60]
The activity source filter has a hard-coded list of data sources. Currently the bindingdb data is now found in searches as it is not in the filter.
We need to add 'BindingDB Database' (src_id = 37) to the filter and also remove Millipore Kinase Screening (src_id = 24).

**Comment by nclopezo** [comment]
I added bindingdb and removed Millipore Kinase Screening

**Comment by agaulton** [comment]
Looks good thanks
