### ISSUE TITLE
Add links to bindingdb on assay report card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#61]
Similar to what we did for pubchem (https://github.com/chembl/user_interface/issues/40)... 
On assay report card, if the src_id = 37 (BindingDB) can we add a link to the bindingdb webpage?
e.g., https://wwwdev.ebi.ac.uk/chembl/assay/inspect/CHEMBL3705111
You can get the relevant IDs from the assays.src_assay_id field. This field takes the form entryid_assayid e.g., '6252_1' for CHEMBL3705111. The BindingDB URL takes the form: https://www.bindingdb.org/jsp/dbsearch/assay.jsp?assayid=1&entryid=6252
So you need to split and swap the two IDs. Hope that makes sense.

**Comment by nclopezo** [comment]
I added the link to bindingdb:

https://wwwdev.ebi.ac.uk/chembl/assay/inspect/CHEMBL3705111

**Comment by agaulton** [comment]
Thanks
