### ISSUE TITLE
Blast not working on dev

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#62]
Do you have the new blast index files? If not let me know...

**Comment by mnowotka** [comment]
Hi,
I generated them but have them on my computer. Let me know where should I copy them.

**Comment by nclopezo** [comment]
The executable files didn't have the correct permissions, I fixed it. Are these files the ones that are mentioned here https://www.ebi.ac.uk/seqdb/confluence/display/CHEMBL/ChEMBL+Interface in the **FASTA files Setup** section?

**Comment by mnowotka** [comment]
Yes, but you need new once that I generated. Just tell me where should I copy them.

**Comment by nclopezo** [comment]
You can copy them to me in dropbox, so I can add and commit them to the repository.

**Comment by mnowotka** [comment]
I'd prefer to rsync it to NFS ;)

**Comment by nclopezo** [comment]
I just sent you the folder route by email.

**Comment by nclopezo** [comment]
I checked some files had not been added correctly to the repository. It should be working now.
