### ISSUE TITLE
Assay description link from bioactivity search results not correct

### ISSUE THREAD

**Issue by apbento** [chembl/user_interface#63]
When displaying the bioactivities for assay chembl_id CHEMBL877864 (for example), the description does not link to the assay report card as expected.

Instead of linking to
https://www.ebi.ac.uk/chembl/assay/inspect/CHEMBL877864,
it tries to link to https://wwwdev.ebi.ac.uk/chembl/assay/inspect/In%20vitro%20inhibitory%20potency%20for%20cholesterol%20synthesis%20was%20measured%20in%20rat%20spleen

**Comment by nclopezo** [comment]
This has been fixed.

**Comment by apbento** [comment]
great. thanks.
