### ISSUE TITLE
USAN Stem missing in 'Browse Drug Targets'

### ISSUE THREAD

**Issue by apbento** [chembl/user_interface#64]
DRUG_TARGETS_MV in both chembl_22_app@CHEMPRO and chembl_app@CHEMREL contains the usan_stem information. However, this is not being displayed on the interface in 'Browse Drug Targets' (https://wwwdev.ebi.ac.uk/chembl/drug/targets).

**Comment by nclopezo** [comment]
This has been fixed:
https://wwwdev.ebi.ac.uk/chembl/drug/targets

**Comment by agaulton** [comment]
great thanks
