### ISSUE TITLE
Patent document search and report card

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#65]
If a simple fix, please could you add 'Patent ID' as a column on the document search results page
e.g., if you do a Document keyword search for 'US-' you will get a list of bindingdb patent documents. These have no pubmed ID or DOI, so would be good to show the patent ID.
Also on the Document Report Card for these, we don't show much information. 
e.g., https://wwwdev.ebi.ac.uk/chembl/doc/inspect/CHEMBL3638922
Would be good to show the patent number and year instead of 'Journal' and display the titles?
This is for documents where DOC.DOC_TYPE = 'PATENT'

**Comment by nclopezo** [comment]
I did the changes and they are in the development server. If it is OK I can deploy it to production:

https://wwwdev.ebi.ac.uk/chembl/doc/inspect/CHEMBL3638922

**Comment by agaulton** [comment]
This all looks good on dev, but on prod I can't get the doc search to return anything. Can you check if this will be fixed if you deploy these changes or a different issue?

**Comment by nclopezo** [comment]
I had forgotten to update the pl/sql search package in the production database. It should be working now.

**Comment by agaulton** [comment]
Looks fine
