### ISSUE TITLE
BLAST doesn't work

### ISSUE THREAD

**Issue by mnowotka** [chembl/user_interface#68]
Hi, BLAST doesn't work, please check this test: https://app.ghostinspector.com/tests/579a07ae088b88da5bb8caa7 but basically this:

    MERAGPSFGQQRQQQQPQQQKQQQRDQDSVEAWLDDHWDFTFSYFVRKATREMVNAWFAE
    RVHTIPVCKEGIRGHTESCSCPLQQSPRADNSAPGTPTRKISASEFDRPLRPIVVKDSEG
    TVSFLSDSEKKEQMPLTPPRFDHDEGDQCSRLLELVKDISSHLDVTALCHKIFLHIHGLI
    SADRYSLFLVCEDSSNDKFLISRLFDVAEGSTLEEVSNNCIRLEWNKGIVGHVAALGEPL
    NIKDAYEDPRFNAEVDQITGYKTQSILCMPIKNHREEVVGVAQAINKKSGNGGTFTEKDE
    KDFAAYLAFCGIVLHNAQLYETSLLENKRNQVLLDLASLIFEEQQSLEVILKKIAATIIS
    FMQVQKCTIFIVDEDCSDSFSSVFHMECEELEKSSDTLTREHDANKINYMYAQYVKNTME
    PLNIPDVSKDKRFPWTTENTGNVNQQCIRSLLCTPIKNGKKNKVIGVCQLVNKMEENTGK
    VKPFNRNDEQFLEAFVIFCGLGIQNTQMYEAVERAMAKQMVTLEVLSYHASAAEEETREL
    QSLAAAVVPSAQTLKITDFSFSDFELSDLETALCTIRMFTDLNLVQNFQMKHEVLCRWIL
    SVKKNYRKNVAYHNWRHAFNTAQCMFAALKAGKIQNKLTDLEILALLIAALSHDLDHRGV
    NNSYIQRSEHPLAQLYCHSIMEHHHFDQCLMILNSPGNQILSGLSIEEYKTTLKIIKQAI
    LATDLALYIKRRGEFFELIRKNQFNLEDPHQKELFLAMLMTACDLSAITKPWPIQQRIAE
    LVATEFFDQGDRERKELNIEPTDLMNREKKNKIPSMQVGFIDAICLQLYEALTHVSEDCF
    PLLDGCRKNRQKWQALAEQQEKMLINGESGQAKRN

return no result.

**Comment by nclopezo** [comment]
I fixed the executable permissions, it should be working now.

**Comment by mnowotka** [comment]
Nope, still failing, check the test.

**Comment by nclopezo** [comment]
I does work. You get 77 results, but CHEMBL2366584 is not in the first page as the test expects. That is why the test fails. If you sort them by chembl id you will find it in page 4.

**Comment by agaulton** [comment]
Could we check that blast results are sorted by ascending e value?
Ta

**Comment by mnowotka** [comment]
+1 we need make the test passing without correcting it.
