### ISSUE TITLE
Update HELM monomer library link

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#69]
Please can we change the HELM monomer library link on the compound pages to point to: ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/releases/chembl_22_1/chembl_22_1_monomer_library.xml instead of ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_21_monomer_library.xml?

Also the HELM Homepage link below it to OpenHELM.org?

e.g., https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1252

**Comment by nclopezo** [comment]
Hi Anna, 

I changed the links: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1252

**Comment by agaulton** [comment]
Sorry, should be ...ChEMBLdb/releases/chembl_22_1...

Also I think the open helm link only works as http://openhelm.org (i.e. no www)

**Comment by nclopezo** [comment]
Ok I fixed them: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1252

**Comment by agaulton** [comment]
Great thanks
