### ISSUE TITLE
Browse Drugs Tab

### ISSUE THREAD

**Issue by anne123** [chembl/user_interface#7]
Suggestion to add information on dates to which drug approvals and USANs have been assigned to this page for each release

**Comment by mark-davies** [comment]
November 2014 data freeze comment added to browse drugs page. Is more information required?

**Comment by mark-davies** [comment]
Updated message to 'Approved Drug Data Freeze: November 2014'

**Comment by agaulton** [comment]
For ChEMBL_21 can we change this to 'Approved Drug Data Freeze: December 2015?

**Comment by ndedman** [comment]
Done

**Comment by agaulton** [comment]
Could we add this to 'Browse Drug Targets' too? Since it is on both of the other drug views...

**Comment by ndedman** [comment]
Done
