### ISSUE TITLE
HELM notation

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#9]
Where the compound is in the biotherapeutics table and helm_notation column is not null, we need to show the helm notation on the report card e.g., molregno=237298/CHEMBL1252

There won't be much overlap at the moment with the existing sequences, but it's possible in future some may have both a sequence and a HELM notation, so I'd keep both for now.

**Comment by mark-davies** [comment]
HELM section added to report card: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL1252

**Comment by mark-davies** [comment]
Add link to monomer library file
